namespace CivicLink.Models
{
    /* 
    * ============================================
    * Generated by Claude 2025-10-14
    * ============================================
    */
    // View model for the events page combining events and search data
    // I asked claude to create my EventsViewModel as its just simply one liners as you can see below, simple task that Claude can do for me.
    public class EventsViewModel
    {
        // All events to display
        public List<Event> Events { get; set; } = new List<Event>();

        // All announcements to show
        public List<Announcement> Announcements { get; set; } = new List<Announcement>();

        // Available categories for filtering
        public HashSet<EventCategory> AvailableCategories { get; set; } = new HashSet<EventCategory>();

        // Unique dates that have events
        public HashSet<DateTime> EventDates { get; set; } = new HashSet<DateTime>();

        // Events recommended based on user searches
        public Queue<Event> RecommendedEvents { get; set; } = new Queue<Event>();

        // Recently viewed events
        public Stack<Event> RecentlyViewed { get; set; } = new Stack<Event>();

        // Current search term if any
        public string SearchTerm { get; set; }

        // Current category filter if any
        public EventCategory? FilterCategory { get; set; }

        // Current date filter if any
        public DateTime? FilterDate { get; set; }
    }
}
